### categorical encoding

In [1]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
cities=["kathmandu","Pokhara","Biratnagar"]
encoded = le.fit_transform(cities)
print(encoded)

[2 1 0]


### one hot encoding


In [2]:
import pandas as pd
df = pd.DataFrame({'source':['river',"lake","well"]})
df_encoded= pd.get_dummies(df,columns=['source'])
print(df_encoded)

   source_lake  source_river  source_well
0        False          True        False
1         True         False        False
2        False         False         True


In [3]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[["poor","fair","good"]])
quality =[['poor'],['good'],['fair']]
encoded = encoder.fit_transform(quality)
print(encoded)

[[0.]
 [2.]
 [1.]]


In [13]:
import numpy as np
import time
x = np.random.random(10000000)
print(x[:5])
start = time.time()
for i in range(x.shape[0]):
    x[i]=x[i]+2
end=time.time()    
print(x[:5])   
print(f"Time Taken is {end-start} seconds ") 

[0.91659692 0.38997999 0.53894133 0.86076446 0.41596624]
[2.91659692 2.38997999 2.53894133 2.86076446 2.41596624]
Time Taken is 0.9566059112548828 seconds 


In [14]:
import numpy as np
import time
x = np.random.random(1000000)
print(x[:5])
start = time.time()

x=x+2
end=time.time()    
print(x[:5])   
print(f"Time Taken is {end-start} seconds ") 

[0.81366324 0.43381821 0.79486523 0.01530733 0.43793733]
[2.81366324 2.43381821 2.79486523 2.01530733 2.43793733]
Time Taken is 0.0011298656463623047 seconds 
